# Generated by Django 4.0.3 on 2024-02-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('perishable', 'Perishable'), ('non-perishable', 'Non-Perishable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='base_distance_in_km',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='fix_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='km_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='zone',
            field=models.CharField(max_length=100),
        ),
    ]
